services:
  - type: web
    name: dealreel-backend
    env: python
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: dealreel-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: dealreel-redis
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true

databases:
  - name: dealreel-db
    region: ohio
    plan: starter
    ipAllowList: []

services:
  - type: redis
    name: dealreel-redis
    region: ohio
    plan: starter
    maxmemoryPolicy: noeviction
    ipAllowList: [] 